### ISSUE TITLE
Compared to existing solution abapGit section

### ISSUE THREAD

**Issue by larshp** [microsoft/abap2git#26]
Hi,
The part

"
Support multiple packages in a Git branch
Support multiple SAP systems in the same Git repo, each in their respective branches
Sync ABAP objects in a released workbench/customizing transport request (shortened as TR below) to specific Git branch
Support configuration changes in customizing transport request
"

All of this is supported in abapGit, suggest updating the readme to reflect this

**Comment by heheng-li** [comment]
#28
